FROM python:3.12-slim

#crear carptea de de trabaojo
WORKDIR /app

#copiar el archivo de requerimientos
COPY requirements.txt .

#instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

#copiar el codigo de la app
COPY ./app ./app 

#exponer el puerto
EXPOSE 5000

#comando para ejcutar la app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
